### ISSUE TITLE
ImportError: cannot import name 'FlashEraser' from 'pyocd.flash.loader'

### ISSUE THREAD

**Issue by maclobdell** [mbedmicro/pyOCD#800]
After updating from 0.23.0 to 024.1, I get the error below.  I've tried uninstalling, reinstalling, removing files in AppData\Roaming\Python\Python37\site-packages\pyocd, etc.  Still same result.

Version: 0.24.1
Python Version: 3.7.4
Windows 10

```
Traceback (most recent call last):
  File "prov_helper_tool.py", line 2, in <module>
    from cysecuretools import CySecureTools
  File "C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\cysecuretools\__init__.py", line 16, in <module>
    from cysecuretools.main import CySecureTools
  File "C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\cysecuretools\main.py", line 24, in <module>
    from cysecuretools.execute.programmer.programmer import ProgrammingTool
  File "C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\cysecuretools\execute\programmer\__init__.py", line 17, in <module>
    from . import programmer
  File "C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\cysecuretools\execute\programmer\programmer.py", line 16, in <module>
    from cysecuretools.execute.programmer.pyocd_wrapper import Pyocd
  File "C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\cysecuretools\execute\programmer\pyocd_wrapper.py", line 22, in <module>
    from pyocd.flash.loader import FlashEraser
ImportError: cannot import name 'FlashEraser' from 'pyocd.flash.loader' (C:\Users\user01\AppData\Roaming\Python\Python37\site-packages\pyocd\flash\loader.py)
```

**Comment by flit** [comment]
This is an incompatibility in cysecuretools. The Python API changed in 0.24.0 to refactor classes in `pyocd.flash.loader` into separate modules. See the [release notes](https://github.com/mbedmicro/pyOCD/releases/tag/v0.24.0) for details.

The Python API is considered unstable until version 1.0 is released. So projects using pyOCD's API should pin their dependency on specific versions.

Sorry for the trouble, but this is necessary to prepare for version 1.0. (It's slow in coming, but regular progress is being made.)

cc @Cypress-OpenOCD
